language: bash
before_install:
  - curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  - apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
  - sudo echo "deb https://dist.crystal-lang.org/apt crystal main" > /etc/apt/sources.list.d/crystal.list
  - sudo apt-get update
  - sudo apt-get install crystal
script:
  - crystal build src/charly.cr --release --stats
  - bin/charly test/main.charly
